baseURL = 'https://blog.freepackets.net/'
languageCode = 'en-us'
title = "William's site"
#theme = "ananke"
#theme = "antora-default-ui-hugo-theme"
#theme = "hugo-theme-relearn"
#theme = "cupper-hugo-theme"
theme = "smol"

sectionPagesMenu = "main"

[security.exec]
allow = ["^asciidoctor$"]

[markup]
  [markup.asciidocext]
    [markup.asciidocext.attributes]
      "icons" = "font"
      "source-highlighter" = "highlightjs"
  [markup.highlight]
    # Disable Goldmark Chroma syntax highlighter
    codeFences = false

[menu]
  [[menu.main]]
        identifier = 'blog'
        name = 'my blog'
        url = '/blog/'
