baseURL = 'https://blog.freepackets.net/'
languageCode = 'en-us'
title = "William's site"
#theme = "ananke"
#theme = "antora-default-ui-hugo-theme"
theme = "hugo-theme-relearn"

sectionPagesMenu = "main"

[security.exec]
allow = ["^asciidoctor$"]

[markup]
  [markup.asciidocext]
    [markup.asciidocext.attributes]
      "icons" = "font"
      "source-highlighter" = "highlightjs"
  [markup.highlight]
    # Disable Goldmark Chroma syntax highlighter
    codeFences = false
